// /ordersData.js

export const ordersData = [
    {
        id: "#CM9801",
        user: { name: "Natali Craig", avatar: "/icons/1.svg" },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "2025-09-21T10:00:00Z",
        status: "In Progress",
    },
    {
        id: "#CM9802",
        user: { name: "Kate Morrison", avatar: "/icons/2.png" },
        project: "CRM Admin pages",
        address: "Terry San Francisco",
        date: "2025-09-21T09:59:00Z",
        status: "Complete",
    },
    {
        id: "#CM9803",
        user: { name: "Drew Cano", avatar: "/icons/3.png" },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "2025-09-21T09:00:00Z",
        status: "Pending",
    },
    {
        id: "#CM9804",
        user: { name: "Orlando Diggs", avatar: "/icons/1.svg" },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "2025-09-20T12:00:00Z",
        status: "Approved",
    },
    {
        id: "#CM9805",
        user: { name: "Andi Lane", avatar: "/icons/2.png" },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "2023-02-02T00:00:00Z",
        status: "Rejected",
    },
    {
        id: "#CM9806",
        user: { name: "Michael Chen", avatar: "/icons/3.png" },
        project: "E-Commerce Website",
        address: "Broadway New York",
        date: "2025-09-19T08:30:00Z",
        status: "In Progress",
    },
    {
        id: "#CM9807",
        user: { name: "Sophia Lee", avatar: "/icons/1.svg" },
        project: "Portfolio Site",
        address: "Lakeview Chicago",
        date: "2025-09-18T11:00:00Z",
        status: "Complete",
    },
    {
        id: "#CM9808",
        user: { name: "James Wilson", avatar: "/icons/2.png" },
        project: "HR Management System",
        address: "Downtown Dallas",
        date: "2025-09-17T15:20:00Z",
        status: "Pending",
    },
    {
        id: "#CM9809",
        user: { name: "Emily Davis", avatar: "/icons/3.png" },
        project: "Marketing Dashboard",
        address: "Pine Street Seattle",
        date: "2025-09-16T19:45:00Z",
        status: "Approved",
    },
    {
        id: "#CM9810",
        user: { name: "Robert Brown", avatar: "/icons/1.svg" },
        project: "Inventory Tracker",
        address: "Sunset Blvd Los Angeles",
        date: "2025-09-15T14:10:00Z",
        status: "Rejected",
    },
    {
        id: "#CM9811",
        user: { name: "Linda Martinez", avatar: "/icons/2.png" },
        project: "Event Planner App",
        address: "Baker Street London",
        date: "2025-09-14T09:25:00Z",
        status: "Complete",
    },
    {
        id: "#CM9812",
        user: { name: "David Kim", avatar: "/icons/3.png" },
        project: "Learning Platform",
        address: "Tech Park San Jose",
        date: "2025-09-13T16:40:00Z",
        status: "In Progress",
    },
    {
        id: "#CM9813",
        user: { name: "Olivia Harris", avatar: "/icons/1.svg" },
        project: "Finance Tracker",
        address: "Main Street Boston",
        date: "2025-09-12T20:55:00Z",
        status: "Pending",
    },
    {
        id: "#CM9814",
        user: { name: "William Scott", avatar: "/icons/2.png" },
        project: "Job Board Website",
        address: "Elm Road Miami",
        date: "2025-09-11T07:15:00Z",
        status: "Approved",
    },
    {
        id: "#CM9815",
        user: { name: "Sophia Turner", avatar: "/icons/3.png" },
        project: "Travel Blog",
        address: "Ocean Drive San Diego",
        date: "2025-09-10T18:00:00Z",
        status: "Rejected",
    },
    {
        id: "#CM9816",
        user: { name: "Daniel Evans", avatar: "/icons/1.svg" },
        project: "Restaurant POS",
        address: "5th Avenue New York",
        date: "2025-09-09T11:35:00Z",
        status: "Complete",
    },
    {
        id: "#CM9817",
        user: { name: "Grace Walker", avatar: "/icons/2.png" },
        project: "Healthcare System",
        address: "Maple Street Toronto",
        date: "2025-09-08T22:10:00Z",
        status: "In Progress",
    },
    {
        id: "#CM9818",
        user: { name: "Henry Adams", avatar: "/icons/3.png" },
        project: "Real Estate CRM",
        address: "King Street Melbourne",
        date: "2025-09-07T13:05:00Z",
        status: "Pending",
    },
    {
        id: "#CM9819",
        user: { name: "Ava Thompson", avatar: "/icons/1.svg" },
        project: "Online Courses",
        address: "Central Park NYC",
        date: "2025-09-06T17:45:00Z",
        status: "Approved",
    },
    {
        id: "#CM9820",
        user: { name: "Ethan White", avatar: "/icons/2.png" },
        project: "Fitness Tracker",
        address: "Hilltop Road Austin",
        date: "2025-09-05T08:20:00Z",
        status: "Rejected",
    },
    {
        id: "#CM9821",
        user: { name: "Mia Johnson", avatar: "/icons/3.png" },
        project: "Chatbot Integration",
        address: "Tech Valley Denver",
        date: "2025-09-04T09:15:00Z",
        status: "Complete",
    },
    {
        id: "#CM9822",
        user: { name: "Noah Brown", avatar: "/icons/1.svg" },
        project: "AI SaaS Dashboard",
        address: "Innovation Hub Boston",
        date: "2025-09-03T11:50:00Z",
        status: "In Progress",
    },
    {
        id: "#CM9823",
        user: { name: "Isabella Clark", avatar: "/icons/2.png" },
        project: "Video Streaming App",
        address: "Hollywood Blvd LA",
        date: "2025-09-02T15:40:00Z",
        status: "Pending",
    },
    {
        id: "#CM9824",
        user: { name: "Lucas Martinez", avatar: "/icons/3.png" },
        project: "Weather Forecast Tool",
        address: "Greenwich London",
        date: "2025-09-01T07:25:00Z",
        status: "Approved",
    },
    {
        id: "#CM9825",
        user: { name: "Emma Taylor", avatar: "/icons/1.svg" },
        project: "Music Streaming Service",
        address: "Downtown Toronto",
        date: "2025-08-31T20:10:00Z",
        status: "Rejected",
    },
]

